   
deploy_production:
  type: deploy
  environment:
    name: production
    url: example.com
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
  # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PROD_SSH")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh ec2-user@$PROD_IP "cd /home/ec2-user/fargate-chron && sudo git checkout production && sudo git pull && sudo rm keys.json && sudo cp keys-prod.json keys.json && $ECR_LOGIN && docker system prune -f && docker build -t fargate-chron-prod . && docker tag fargate-chron-prod:latest {account}.dkr.ecr.ca-central-1.amazonaws.com/fargate-chron-prod:latest && docker push {account}.dkr.ecr.ca-central-1.amazonaws.com/fargate-chron-prod:latest && exit"
  only:
    - production
    
deploy_development:
  type: deploy
  environment:
    name: development
    url: example.com
  before_script:
    - apt-get update -qq
    - apt-get install -qq git
  # Setup SSH deploy keys
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEV_SSH")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh ec2-user@$DEV_IP "cd /home/ec2-user/fargate-chron && sudo git checkout development && sudo git pull && sudo rm keys.json && sudo cp keys-dev.json keys.json && $ECR_LOGIN && docker system prune -f && docker build -t fargate-chron-dev . && docker tag fargate-chron-dev:latest {prod-account}.dkr.ecr.ca-central-1.amazonaws.com/fargate-chron-dev && docker push {prod-account}.dkr.ecr.ca-central-1.amazonaws.com/fargate-chron-dev:latest && exit"
  only:
    - development
    

